DefectClass:
- Good
- Surface
ImageFormat:
- 1.Area
- 2.Length
- 3.Width
- 4.Device
- 5.LotId
- 7.ImageName
IsDevice: 1
Supplier:
- Front_M6
- Front_M6_val
- FrontDark_M6
- FrontDark_M6_val
- Back_M6
- Back_M6_val
