# att: 不要在 关键字 同行加注释
# 1. init config
iteration: 1
epochs: 5
cuda_device: [3]
model_name: "eca_nfnet_l0"
model_path: "./model_path/JCET_AOI_NTech.pth"
classes_path: ["./model_path/classsfication.txt", "./model_path/MultiClassification.txt"]

# 2. train config
batch_size: 32
model_train_transform: [["RandomAffine", "Resize-512", "Pad-16", "ColorJitter", "RandomCrop-512"]]
model_val_transform: [["Resize-512"]]
acc_save_thresh: 0.95
cuda_num_workers: 8
device_max_thresh: 400
device_min_thresh: 30
train_val_rate: 0.9
use_focalloss: False
lr: 0.0001
factor: 0.5
patience: 2
Illegal_keywords: ["test", "3d"]

# 3.special set
# 模型训练前过滤temp的Good目录 括号参数说明：是否启用、保留Good大于0.7
TempGoodDirModelFilt: [True, 0.7]
# 训练结束后清理数据 括号参数说明：是否启用、训练结束后清理数据，保留Good/Bad1000张图
IsClearDatasTrainEnd: [True, 1000]
# 训练结束后是否动态增加缺陷数据 括号参数说明：是否启用、增加最后的结果数量
IsAutoAddDefect: [True, 150, "defectpath"]

# 4.全自动迭代配置-start
IsStartAutoIter: False
# 判断当前 日期减开始日期 是否大于等于七天，  是则进行拉取数据迭代模型，迭代完成后更新 count_start_time 日期
count_start_time: "2023-10-01"
interval_day: 7
count_device_wafers_min: 5
device_overkill_threshold: 500
device_overkill_select_num: 500
device_underkill_threshold: 5
# 加入未加入训练的device
check_device_min: 55
new_device_image_num: 450
# 全自动迭代配置-end

# eagle-database config
eagle_export_process: 8
eagle_host: "DESKTOP-UFKCQ3O"
eagle_user: "sa"
eagle_password: "sql2005"
eagle_database: "EagleDb_JCET_JCAP"
